infobox <- function(title, text) {
  tags$div(class = "custom-aside-container",
        tags$div(class = "custom-aside",
            tags$svg(xmlns = "http://www.w3.org/2000/svg",
                width = "32",
                height = "32",
                viewbox = "0 0 24 24",
                fill = "none",
                stroke = "currentColor",
                `stroke-width` = "2",
                `stroke-linecap` = "round",
                `stroke-linejoin` = "round",
                tags$circle(cx = "12",
                       cy = "12",
                       r = "10"),
                tags$line(x1 = "12",
                     y1 = "16",
                     x2 = "12",
                     y2 = "12"),
                tags$line(x1 = "12",
                     y1 = "8",
                     x2 = "12.01",
                     y2 = "8"))),
        tags$strong(class = "aside-title", title),
        text
  )
}